name: Feature Request
description: Suggest an enhancement for the Lovelace card
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > If your feature request is related to **Home Assistant integration features** or the **underlying Python library**, please submit it in their respective repositories:
        > - [Integration Features](https://github.com/selvakk2k/ha-miraie-ac-in/issues)
        > - [Python Library Features](https://github.com/selvakk2k/miraie-ac-in/issues)
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: A clear and concise description of what the limitation is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: dropdown
    id: physical_device
    attributes:
      label: Can you test this against a physical device?
      description: Card styling changes often require testing against real device state values.
      options:
        - "Yes, I own a Panasonic AC and can test/capture screenshots."
        - "No, I do not have a physical device to test with."
    validations:
      required: true
